name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Run
      #   run: cargo run --release

      - name: Run C
        run: $(brew --prefix llvm)/bin/clang main.c `pkg-config libusb-1.0 --libs` `pkg-config libusb-1.0 --cflags` -O3 -o main && ./main
